artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://files.grouplens.org/datasets/movielens/ml-20m.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion
  STATUS_FILE: artifacts/data_validation/status.txt
  all_schema:
    ratings:
      userId: int64
      movieId: int64
      rating: float64
      timestamp: int64
    movies:
      movieId: int64
      title: object
      genres: object


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion


feature_engineering:
  root_dir: artifacts/Feature_engineering
  data_path: artifacts/data_transformation  